# Generated by Django 3.1.3 on 2020-11-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='central_model',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='central_model',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='central_model',
            name='maritual_state',
            field=models.CharField(max_length=15),
        ),
    ]
