# Generated by Django 3.1.3 on 2020-12-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_organization', '0002_auto_20201104_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='central_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
