# Generated by Django 3.1.3 on 2020-12-02 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('central_organization', '0003_auto_20201202_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='central_model',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
